name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { env: seeed_xiao_esp32c3 }
          - { env: seeed_xiao_esp32s3 }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Build
        run: platformio run -e ${{ matrix.env }}
      - name: Archive binaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.env }}
          path: .pio/build/**/*.bin
